"""initial migration

Revision ID: 20251030003544
Revises: 
Create Date: 2025-10-30 00:35:44.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251030003544'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('linked_id', sa.Integer(), nullable=True),
    sa.Column('link_precedence', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linked_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email', 'contacts', ['email'])
    op.create_index('idx_linked_id', 'contacts', ['linked_id'])
    op.create_index('idx_phone_number', 'contacts', ['phone_number'])
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index('idx_phone_number', table_name='contacts')
    op.drop_index('idx_linked_id', table_name='contacts')
    op.drop_index('idx_email', table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###